/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.newardassociates.cerbosdemo;

import java.util.*;
import dev.cerbos.sdk.*;
import dev.cerbos.sdk.builders.*;
import static dev.cerbos.sdk.builders.AttributeValue.*;

class User {
    public String username;
    public String role;

    public User(String u, String r) { username = u; role = r; }
}

public class App {
    private CerbosBlockingClient client; 
    private String greeting = "Hello world!";

    User user = new User("nobody", "nothing");
        // package-private for easier testing
        // default user can do nothing

    public App() {
        try {
            client = new CerbosClientBuilder("localhost:3593").withPlaintext().buildBlockingClient();
        }
        catch (Exception ex) {
            throw new RuntimeException("Cerbos is not configured correctly!", ex);
        }
    }

    public boolean authorized(String action) {
        CheckResult result = client.check(
            Principal.newInstance("john","user"),       // Principal
            Resource.newInstance("greeting"));          // Resource

        return result.isAllowed(action);                // Action
    }

    public String getGreeting() {
        // Only return the greeting if the user is permitted to see it
        if (authorized("read")) {
            return greeting;
        }
        return "You are not authorized to view this greeting!";
    }
    public String setGreeting(String value) {
        // Only return the greeting if the user is permitted to see it
        if (authorized("update")) {
            greeting = value;
            return greeting;
        }
        return "You are not authorized to change this greeting!";
    }

    public static void main(String[] args) {
        App app = new App();

        Scanner sc= new Scanner(System.in);

        // Let's pretend this is really secure
        System.out.println("Please type in your username: ");
        String str1 = sc.nextLine();  
        System.out.println("Please type in your user role: ");
        String str2 = sc.nextLine();
        app.user = new User(str1, str2);

        System.out.println("Let's try to view the greeting!");
        System.out.println(app.getGreeting());

        System.out.println("Let's try to change the greeting!");
        System.out.println(app.setGreeting("Howdy!"));
    }
}
